notifications:
  email: false
language: node_js
sudo: false
addons:
  apt:
    packages:
      - expect-dev
      - lftp
cache:
  directories:
    - i7
    #- Inform
before_install:
  # Travis will make an empty i7 directory because we are caching it, so remove it
  - "[[ ! $(ls -A i7) ]] && rmdir i7 || true"
install:
  - make setup
script:
  - make Kerkerkruip.gblorb
  - ./tools/travis_tests
after_script:
  - openssl aes-256-cbc -K $encrypted_f8c474e594c4_key -iv $encrypted_f8c474e594c4_iv
    -in .travis/kerkerkruip_rsa.enc -out .travis/kerkerkruip_rsa -d
  - chmod 600 .travis/kerkerkruip_rsa
  - eval $(ssh-agent -s) && ssh-add .travis/kerkerkruip_rsa
  - if [[ $TRAVIS_REPO_SLUG == i7/kerkerkruip ]] && [[ $TRAVIS_BRANCH == master ]] &&
    [[ $TRAVIS_PULL_REQUEST == false ]]; then make deploy; fi
