language: node_js
sudo: false
addons:
  apt:
    packages:
    - expect-dev
    - sshpass
install: ./tools/travis_install
script:
    - ./tools/travis_build
    - ./tools/travis_tests
notifications:
    email: false
